spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
management:
  endpoint:
    health:
      show-details: always # 显示健康详情
